version: "3.9"

services:
  db:
    image: postgres
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - TZ=Asia/Seoul
      - POSTGRES_DB=dress
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "7718:5432"

networks:
  default:
    name: omil_network