version: "3.9"

services:
  backend:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./backend/WEB:/home/backend
  version: "3.8"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes: 
      - ./:/home/app
    ports:
      - "8080:3000"
