version: "3.9"

# 실서버에서 사용하는 환경

services:
  db:
    container_name: omil_db
    image: mysql
    restart: always
    env_file: .env.private
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 100

  backend:
    container_name: omil_backend
    build:
      context: backend/deploy
      dockerfile: Dockerfile
    env_file: .env.private
    volumes:
      - ${BACKEND_DIR_PATH}:/home/backend
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: omil_frontend
    build:
      context: frontend/deploy
      dockerfile: Dockerfile
    env_file: .env.private
    volumes:
      - ${FRONTEND_DIR_PATH}:/home/frontend
    ports:
      - "${FRONTEND_PORT}:8080"
