version: "3.9"

# code server에서 사용하는 환경

services:
  db:
    container_name: omil_db
    image: mysql
    # restart: always
    env_file: .env.private

  backend: 
    container_name: omil_backend
    build:
      context: backend/deploy
      dockerfile: dev_Dockerfile
    env_file: .env.private
    volumes:
      - omil:/home
    depends_on:
      - db
    ports:
      - "7776:8000"
  frontend:
    container_name: omil_frontend
    build:
      context: frontend/deploy
      dockerfile: dev_Dockerfile
    env_file: .env.private
    volumes:
      - omil:/home
    ports:
      - "7777:8080"


volumes:
  omil: # 개발용 code server volume
    external:
      name: omil