version: "3.9"

services:
  db:
    # container_name: omil_db
    image: mysql
    # restart: always
    env_file: .env.private

  backend:
    container_name: omil_backend
    build:
      context: backend/deploy
      dockerfile: dev_Dockerfile
    env_file: .env.private
    depends_on:
      - db
    ports:
      - "8081:8000"
  frontend:
    container_name: omil_frontend
    build:
      context: frontend/deploy
      dockerfile: dev_Dockerfile
    env_file: .env.private
    ports:
      - "8080:8080"
