version: "3.9"

services:
  db:
    image: postgres:14.1
    # volumes:
    #   - ./data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./:/home/backend/WEB_CLOUD_OhmilZomil_NAVYeffect/WEB_BE

networks:
  default:
    name: omil_network
