
name: Build and deploy Python app 

on: 
  push:            
    branches: [ "main" , "dev/devops"]

jobs:
  React-Build-ssh-action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}          
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_PW }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            cd /config/workspace/WEB_CLOUD_OmilZomil_NAVYeffect/
            sh build.sh
            sh start.sh